# Apache Configuration
- name: Create document root
  become: yes
  file:
    path: '/var/www/{{ http_host }}'
    state: directory
    owner: 'www-data'
    group: 'www-data'
    mode: '0755'
  tags: [ apache ]

- name: Set up Apache VirtualHost
  become: yes
  template:
    src: 'apache.conf'
    dest: '/etc/apache2/sites-available/{{ http_conf }}'
  notify: Reload Apache
  tags: [ apache ]

- name: Enable rewrite module
  become: yes
  shell: /usr/sbin/a2enmod rewrite
  notify: Reload Apache
  tags: [ apache ]

- name: Enable new site
  become: yes
  shell: /usr/sbin/a2ensite {{ http_conf }}
  notify: Reload Apache
  tags: [ apache ]

- name: Disable default Apache site
  become: yes
  shell: /usr/sbin/a2dissite 000-default.conf
  notify: Restart Apache
  tags: [ apache ]